# src/AppBundle/Resources/config/api_resources/resources.yml

# AppBundle\Entity\APIReference:
#     itemOperations:
#         get:
#             method: 'GET'
#         post:
#             method: 'POST'
#     collectionOperations:
#         get:
#             method: 'GET'
#         post:
#             method: 'POST'
#         special:
#             route_name: 'api_post'

AppBundle\Entity\ApiRef:
     collectionOperations:
         special:
             # method: 'PUT'
             route_name: 'api_ref_action'
             hydra_context: { "testhydra":"Action" }
         get:
             method: 'GET'
             hydra_context: { foo: 'Action' }

AppBundle\Entity\SoftwareApplication:
    collectionOperations:
        get:
             method: 'GET'
             hydra_context: { foo: 'Action' }
        put:
             method: 'PUT'
             route_name: 'api_graph_upload_action'
             hydra_context: { foo: 'Action' }
    itemOperations:
        get:
            method: 'GET'
            route_name: 'api_graph_retrieve_action'
        put:
            method: 'PUT'
        delete:
            method: 'DELETE'
            route_name: 'api_graph_delete_action'
