# src/AppBundle/Resources/config/api_resources/resources.yml

# AppBundle\Entity\APIReference:
#     itemOperations:
#         get:
#             method: 'GET'
#         post:
#             method: 'POST'
#     collectionOperations:
#         get:
#             method: 'GET'
#         post:
#             method: 'POST'
#         special:
#             route_name: 'api_post'

AppBundle\Entity\ApiDiscovery:
    collectionOperations:
        match_test:
            method: 'PUT'
            route_name: 'api_test_match_action'
        match:
             method: 'PUT'
             route_name: 'api_match_action'
    itemOperations:

# AppBundle\Entity\SoftwareApplication:
#     collectionOperations:
#         get:
#              method: 'GET'
#         put:
#             method: 'PUT'
#             route_name: 'api_match_action'
#     itemOperations:
#         get:
#             method: 'GET'
#             route_name: 'api_graph_retrieve_action'

AppBundle\Entity\SoftwareApplicationTesting:
    collectionOperations:
        get:
             method: 'GET'
        # test_upload_graph:
        #      method: 'PUT'
        #      route_name: 'api_test_match_action'
        test_upload_graph:
            method: 'PUT'
            route_name: 'api_test_upload_action'
    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'
        delete_graph:
            method: 'DELETE'
            route_name: 'api_test_delete_action'
