api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

# douleue, kaiden afhne..
api_special:
    path: '/api_test/upload'
    methods:  ['PUT']
    defaults:
        _controller: 'AppBundle:SoftwareApplicationTesting:test_upload_graph'
        _api_resource_class: 'AppBundle\Entity\SoftwareApplicationTesting'
        _api_collection_operation_name: 'test_upload_graph'