# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    api_key: segamw
#    parameter_name: value

services:

# de xreiasthke
    # action_api_ref_action:
    #     class:     AppBundle\Action\ApiRefAction
    #     arguments: ["@request_stack"]

    classes.vocs_search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { vocabulary: 'exact', url: 'iend' } ]
        tags:      [ { name: 'api_platform.filter', id: 'statsclass.search' } ]

    api_ref_action:
        class: 'AppBundle\Action\ApiRefAction'
        arguments: ["@request_stack", "%api_key%"]
        # tags:
        #     -  { name: 'api_platform.collection_data_provider', priority: 1 }

    # geo_coordinates.custom_geo_filter:
    #     class: 'AppBundle\Filter\CustomGeoFilter'
    #     tags:  [ { name: 'api_platform.filter', id: 'geo_coordinates.geo' } ]

#    offer.order_filter:
#        parent:    "api_platform.doctrine.orm.order_filter"
#        arguments: [ { "price": "ASC" } ]

# estate.doctrine_file_listener:
#         class: estateBundle\EventListener\ImageUploadListener
#         arguments: ['%argument_gkountas%', '%argument_mitsos%']