# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sparql_host: http://0.0.0.0:8900/
    readonly_dataset: thesis
    test_dataset: testing
    # sparql_readonly: http://0.0.0.0:8900/thesis
    # sparql_testing: http://0.0.0.0:8900/testing

services:

    classes.vocs_search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { vocabulary: 'exact', url: 'ipartial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'statsclass.search' } ]

    soft_apps.vocs_search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { description: 'ipartial', name: 'ipartial', url: 'exact', applicationCategory: 'ipartial', applicationSubCategory: 'ipartial', isAccessibleForFree: 'exact', aggregateRating: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'soft_apps.search' } ]

    AppBundle\Action\ApiDiscoveryTestMatchAction:
        autowire: true
        public: true
        arguments: ["@request_stack", "%sparql_host%", "%test_dataset%"]

    AppBundle\Action\ApiDiscoveryMatchAction:
        autowire: true
        public: true
        arguments: ["@request_stack", "%sparql_host%", "%readonly_dataset%"]
